export enum CrimeType {
  SHOPLIFT = "SHOPLIFT", //"shoplift",
  ROB_STORE = "ROBSTORE", //"rob a store",
  MUG = "MUG", //"mug someone",
  LARCENY = "LARCENY", //"commit larceny",
  DRUGS = "DRUGS", //"deal drugs",
  BOND_FORGERY = "BONDFORGERY", //"forge corporate bonds",
  TRAFFIC_ARMS = "TRAFFICKARMS", //"traffick illegal arms",
  HOMICIDE = "HOMICIDE", //"commit homicide",
  GRAND_THEFT_AUTO = "GRANDTHEFTAUTO", //"commit grand theft auto",
  KIDNAP = "KIDNAP", //"kidnap someone for ransom",
  ASSASSINATION = "ASSASSINATION", //"assassinate a high-profile target",
  HEIST = "HEIST", //"pull off the ultimate heist",
}

export enum CompanyPosNames {
  sw0 = "Software Engineering Intern",
  sw1 = "Junior Software Engineer",
  sw2 = "Senior Software Engineer",
  sw3 = "Lead Software Developer",
  sw4 = "Head of Software",
  sw5 = "Head of Engineering",
  sw6 = "Vice President of Technology",
  sw7 = "Chief Technology Officer",
  IT0 = "IT Intern",
  IT1 = "IT Analyst",
  IT2 = "IT Manager",
  IT3 = "Systems Administrator",
  secEng = "Security Engineer",
  netEng0 = "Network Engineer",
  netEng1 = "Network Administrator",
  bus0 = "Business Intern",
  bus1 = "Business Analyst",
  bus2 = "Business Manager",
  bus3 = "Operations Manager",
  bus4 = "Chief Financial Officer",
  bus5 = "Chief Executive Officer",
  sec0 = "Police Officer",
  sec1 = "Police Chief",
  sec2 = "Security Guard",
  sec3 = "Security Officer",
  sec4 = "Security Supervisor",
  sec5 = "Head of Security",
  agent0 = "Field Agent",
  agent1 = "Secret Agent",
  agent2 = "Special Operative",
  waiter = "Waiter",
  employee = "Employee",
  softCons0 = "Software Consultant",
  softCons1 = "Senior Software Consultant",
  busCons0 = "Business Consultant",
  busCons1 = "Senior Business Consultant",
  waiterPT = "Part-time Waiter",
  employeePT = "Part-time Employee",
}
