export enum CrimeType {
  None = "",
  Shoplift = "shoplift",
  RobStore = "rob a store",
  Mug = "mug someone",
  Larceny = "commit larceny",
  Drugs = "deal drugs",
  BondForgery = "forge corporate bonds",
  TraffickArms = "traffick illegal arms",
  Homicide = "commit homicide",
  GrandTheftAuto = "commit grand theft auto",
  Kidnap = "kidnap someone for ransom",
  Assassination = "assassinate a high-profile target",
  Heist = "pull off the ultimate heist",
}
