export const FconfSettings = {
  ENABLE_BASH_HOTKEYS: false,
  ENABLE_TIMESTAMPS: false,
  MAIN_MENU_STYLE: "default",
  THEME_BACKGROUND_COLOR: "#000000",
  THEME_FONT_COLOR: "#66ff33",
  THEME_HIGHLIGHT_COLOR: "#ffffff",
  THEME_PROMPT_COLOR: "#f92672",
  WRAP_INPUT: false,
};
